---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/":
    get:
      summary: list bikes
      responses:
        '200':
          description: successful
  "/bikes":
    get:
      summary: list bikes
      responses:
        '200':
          description: successful
    post:
      summary: create bike
      responses:
        '200':
          description: successful
  "/bikes/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show bike
      responses:
        '200':
          description: successful
    patch:
      summary: update bike
      responses:
        '200':
          description: successful
    delete:
      summary: delete bike
      responses:
        '200':
          description: successful
  "/locations":
    get:
      summary: list locations
      responses:
        '200':
          description: successful
    post:
      summary: create location
      responses:
        '200':
          description: successful
  "/locations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show location
      responses:
        '200':
          description: successful
    patch:
      summary: update location
      responses:
        '200':
          description: successful
    delete:
      summary: delete location
      responses:
        '200':
          description: successful
  "/reservations":
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
    post:
      summary: create reservation
      responses:
        '200':
          description: successful
  "/reservations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show reservation
      responses:
        '200':
          description: successful
    patch:
      summary: update reservation
      responses:
        '200':
          description: successful
    delete:
      summary: delete reservation
      responses:
        '200':
          description: successful
  "/users/sign_up":
    post:
      summary: create registration
      responses:
        '200':
          description: successful
  "/users/sign_in":
    post:
      summary: create session
      responses:
        '200':
          description: successful
  "/users/sign_out":
    delete:
      summary: delete session
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
